---
- name: Playbook used to setup dns on top of rhel
  hosts: all
  gather_facts: yes
  collections:
    - rhel.repos
  tasks:
    - name: Import a role
      ansible.builtin.import_role:
        name: dns
