---
- name: Playbook used to deploy wordpress and mariadb server
  hosts: all
  roles:
    - rhel.repos.dns
  #tasks:
   # - name: Welcome to my application using collection role
    #  debug:
     #   msg: "Welcome to collection and roles application"
    #- name: Import a role
     # ansible.builtin.import_role:
      #  name: dns
